version: '3'
services:

  # Spring boot backend
  backend:
    image: travelblog-backend
    container_name: travelblog-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    logging:
      driver: json-file
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "7001:3306"
    environment:
      MYSQL_DATABASE: travelblog
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      app-network:
        aliases:
          - db

  # Redis server
  redis:
    image: redis:5.0.3-alpine
    container_name: travelblog-redis
    ports:
      - "7000:6379"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local
